### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by benoffi7** [nitrico/FontBinder#2]
Hi! When I run the app this error appears

```
C:\Users\Gonzalo\AndroidStudioProjects\firebase\app\build\intermediates\data-binding-layout-out\debug\layout\fragment_edit_name.xml

Error:(19) No resource identifier found for attribute 'font' in package 'android'
```

I have

```


            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textAppearance="?android:attr/textAppearanceMedium"
                android:text="Fecha"
                android:font='@{"avquest"}'
                android:id="@+id/textView"
                tools:ignore="MissingPrefix" />
```

In my gradle I add

 dataBinding {
        enabled true
    } 

and

```
compile 'com.github.nitrico.fontbinder:fontbinder:1.0.3'
```

Thanks!

**Comment by benoffi7** [comment]
In my Fragment have this

```
    View view = DataBindingUtil.inflate(R.layout.fragment_edit_name, container);
```

**Comment by nitrico** [comment]
Hi @benoffi7 

Can you show here the build.gradle file for your app module?

**Comment by benoffi7** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "23.0.3"

```
defaultConfig {
    applicationId "com.coffeeandcookies.firebase"
    minSdkVersion 15
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
    multiDexEnabled true
}

dataBinding {
    enabled true
}


buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }

    debug {
        debuggable true
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.github.clans:fab:1.6.2'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:design:24.1.1'
    compile 'com.android.support:recyclerview-v7:24.1.1'
    compile 'com.google.android.gms:play-services-auth:9.2.1'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.firebase:firebase-client-android:2.3.1'
    compile 'com.firebaseui:firebase-ui:0.2.0'
    compile 'com.google.firebase:firebase-messaging:9.0.1'
    compile 'com.google.firebase:firebase-auth:9.0.2'
    compile 'com.google.android.gms:play-services:9.2.1'
    compile 'com.github.nitrico.fontbinder:fontbinder:1.0.3'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.drivemode:TypefaceHelper:1.2.0@aar'}

apply plugin: 'com.google.gms.google-services'

**Comment by nitrico** [comment]
I think you are not using the `DataBindingUtil.inflate` method correctly.

Let's say your fragment is called `MainFragment` and the layout for that fragment is `fragment_main.xml` which is using the `<layout>` tag as root. Then, the Data Binding library will create a class called `FragmentMainBinding` and you should inflate the view like this:

``` java
@Nullable
@Override
public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
    FragmentMainBinding binding = DataBindingUtil.inflate(inflater, R.layout.fragment_main, container, false);
    return binding.getRoot();
}
```

Let me know it that was the problem.

**Comment by benoffi7** [comment]
Error:(58, 9) error: cannot find symbol class FragmentMainBinding

**Comment by nitrico** [comment]
What's the filename of your fragment layout?

**Comment by benoffi7** [comment]
fragment_edit_name is the xml

EditNameDialog is the DialogFragment java class

**Comment by nitrico** [comment]
Then you should use the class FragmentEditNameBinding which is created automatically by the Data Binding library (instead of the FragmentMainBinding used as an example)

**Comment by benoffi7** [comment]
Error:(58, 9) error: cannot find symbol class FragmentEditNameDialogBinding

Error:(58, 9) error: cannot find symbol class FragmentEditNameBinding

**Comment by benoffi7** [comment]
`public class EditNameDialog extends DialogFragment`

**Comment by nitrico** [comment]
Are you using the `<layout>` tag in your layout file?

``` xml
<layout xmlns:android="http://schemas.android.com/apk/res/android" >

    <!-- your actual layout here -->

</layout>
```

If so, try cleaning / rebuilding / making the project before using this WhateverBinding class and it should then appear.

**Comment by benoffi7** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android" >
<LinearLayout
    android:orientation="vertical" android:layout_width="match_parent"
    android:padding="10sp"
    android:layout_height="match_parent">

    <TableLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:stretchColumns="*"
        android:layout_weight="1">

        <TableRow
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            >

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textAppearance="?android:attr/textAppearanceMedium"
                android:text="Fecha"
                android:font='@{"avquest"}'
                android:id="@+id/textView"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textAppearance="?android:attr/textAppearanceMedium"
                android:text="Pulsa para agregar una fecha"
                android:id="@+id/textView_fecha" />
        </TableRow>

        <View android:layout_height="1dp" android:layout_marginTop="10dp" android:layout_width="match_parent" android:background="@android:color/darker_gray"/>


        <TableRow
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            >

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textAppearance="?android:attr/textAppearanceMedium"
                android:text="Nombre del evento"
                android:id="@+id/textView_nombre"
                android:layout_gravity="center" />

            <EditText
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textAppearance="?android:attr/textAppearanceMedium"

                android:id="@+id/edit_nombre" />
        </TableRow>

        <View android:layout_height="1dp" android:layout_marginTop="10dp" android:layout_width="match_parent" android:background="@android:color/darker_gray"/>

    </TableLayout>

    <Button
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Agregar"
        android:id="@+id/button_add" />
</LinearLayout>
    </layout>
```

**Comment by benoffi7** [comment]
What is the correct name for the type of binding variable ?

**Comment by benoffi7** [comment]
With

ViewDataBinding binding = DataBindingUtil.inflate(inflater, R.layout.fragment_edit_name, container, false);

**Comment by nitrico** [comment]
It should be the camelcased version of the layout xml file. That's the binding class, not the binding variable.

I was going to suggest you using the ViewDataBinding class... Did it work?

https://developer.android.com/topic/libraries/data-binding/index.html#generated_binding

**Comment by benoffi7** [comment]
![device-2016-08-01-124019](https://cloud.githubusercontent.com/assets/971363/17299536/22822552-57e5-11e6-8408-70f5546fe3bb.png)

**Comment by nitrico** [comment]
Cool :)

Por cierto, puedes usar también `android:font` para todo lo que herede de TextView: EditText, Button... ;)

**Comment by benoffi7** [comment]
Excelente! Muchas gracias por la ayuda!!!

Ya estaba haciendo el java para todos los textview y componentes de una super app. Me ahorra mucho esto!

**Comment by nitrico** [comment]
De nada! 

Me alegro mucho de que te sirva.
